[global/wm]
margin-top = 0
margin-bottom = 0

[settings]
compositing-background = source
compositing-border = over
compositing-foreground = over
compositing-overline = over
compositing-underline = over

pseudo-transparency = true

screenchange-reload = false

throttle-input-for = 30
throttle-output = 5
throttle-output-for = 10

; assets
include-file = ~/.config/polybar/etc/assets.ini
include-file = ~/.config/polybar/etc/color.ini
include-file = ~/.config/polybar/etc/base.ini

; bar
include-file = ~/.config/polybar/bar/i3.ini

; modules
include-file = ~/.config/polybar/modules/i3.ini
include-file = ~/.config/polybar/modules/date.ini
include-file = ~/.config/polybar/modules/mode.ini
include-file = ~/.config/polybar/modules/tray.ini
include-file = ~/.config/polybar/modules/network.ini
include-file = ~/.config/polybar/modules/text.ini
include-file = ~/.config/polybar/modules/cpu.ini
include-file = ~/.config/polybar/modules/volume.ini
include-file = ~/.config/polybar/modules/window.ini