[etc/base]
; global
format-prefix-background = ${color.yellow}
format-prefix-foreground = ${color.black}

format-suffix-background = ${color.white}
format-suffix-foreground = ${color.black}

label-background = ${color.white}
label-foreground = ${color.black}